log:
  level: "INFO"
  fileName: "test.log"
  maxSize: 10
  maxAge: 30
  maxBackups: 10
  logType: "console"

main:
  mode: "release"
  port: 19000
  address: "127.0.0.1"
  context: "/api/v1"

mysql:
  user: "root"
  password: "dreamtechIT2017"
  host: "10.81.69.77"
  port: 3306
  db: "sql_test"
  otherOptions: "charset=utf8mb4&parseTime=True"
  maxOpenConns: 20
  maxIdleConns: 10

redis:
  password: "TA6sMiuSRqtTrHB7Amdg"
  host: "10.81.69.77:32584"
  cluster: false
  db: 1
  poolSize: 20



